language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_5aa0ff0f8511_key -iv $encrypted_5aa0ff0f8511_iv
  -in id_rsa.enc -out id_rsa -d
- cd web
script:
- npm run travis-test
- npm run prod-build
after_success:
- eval $(ssh-agent -s)
- chmod 600 ../id_rsa
- ssh-add ../id_rsa
- ssh-keyscan -p ${port} ${addr} >> ~/.ssh/known_hosts
- ssh -p ${port} root@${addr} "rm -rf /opt/bside/httpd/htdocs/*"
- scp -P ${port} -r dist/web/* root@${addr}:/opt/bside/httpd/htdocs
notifications:
  email: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
addons:
  chrome: stable
dist: trusty
sudo: required
